try:
    a=345/10
except Exception as e:
    print(e)
else:  # this will execute if there is no exception 
    # gets executed when there is no error in the try block
    print("hey I am good")

